executor: "cluster-generic"
jobscript: "grid-jobscript.sh"
cluster-generic-submit-cmd: "grid-submit.py"
cluster-generic-status-cmd: "grid-status.py"
max-jobs-per-second: 100
max-status-checks-per-second: 100
restart-times: 5
local-cores: 10
jobs: 5000
verbose: false
latency-wait: 120
